Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mosdong.Data;
using Mosdong.Utility;

namespace Mosdong.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.ManagerUser)]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return View(await _db.ApplicationUser.Where(u=>u.Id != claim.Value).ToListAsync());
        }

        public async Task<IActionResult> Lock(string id)
        {
            if(id==null)
            {
                return NotFound();
            }

            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);
            if(applicationUser==null)
            {
                return NotFound();
            }

            applicationUser.LockoutEnd = DateTime.Now.AddYears(1000);

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            applicationUser.LockoutEnd = DateTime.Now;

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
    }
}

ViewComponents/TopNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mosdong.Data;
using Mosdong.Models.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace Mosdong.ViewComponents
{
    public class TopNavViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _db;

        public TopNavViewComponent (ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {

            NavListViewModel model = new NavListViewModel
            {
                NavCategory = await _db.Category.ToListAsync(),                
                NavSubCategory = await _db.SubCategory.OrderBy(p => p.Name).ToListAsync(),
                NavMiniCategory = await _db.MiniCategory.OrderBy(m => m.Name).ToListAsync(),
                SubCategory = new Models.SubCategory()
            };

            return View(model);

        }
    } 
}

Views/Shared/_CreateAndBackToListButtonPartial.cshtml
<div class="col-6">
    <input type="submit" class="btn btn-primary form-control" value="추가" />
</div>
<div class="col-6">
    <a asp-action="Index" class="btn btn-secondary form-control">목록</a>
</div>

Views/Shared/_CreateButton.cshtml
<p>
    <a asp-action="Create" class="btn btn-outline-primary"><i class="fas fa-plus"></i>&nbsp;추가하기</a>
</p>

Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-outline-primary"><i class="fas fa-plus"></i>&nbsp;추가하기</a>
</p>

Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="삭제하기" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-secondary form-control">목록으로</a>
    </div>
</div>

Views/Shared/_DeleteAndBackToListButtonPartial.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="삭제하기" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-secondary form-control">목록으로</a>
    </div>
</div>

Views/Shared/_EditAndBackToListButton.cshtml
@model int


    <div class="col-6">
        <input type="submit" class="btn btn-primary form-control" asp-route-id="@Model" value="편집" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-secondary form-control">목록</a>
    </div>

Views/Shared/_EditAndBackToListButtonPartial.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-primary form-control" asp-route-id="@Model" value="편집" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-secondary form-control">목록</a>
    </div>
</div>

Views/Shared/_IndexHitItemsPartial.cshtml
@model IEnumerable<ProductItemModel>

@if (Model.Count() > 0)
{
         <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px">
            
             <h5 class="text-dark"><span class="badge badge-pill badge-warning">Hit</span> &nbsp;인기상품</h5>
            
                <div class="row">

                    @foreach (var product in Model.Where(p => p.ProductAd == "2" && p.IsNotVisible == false).OrderByDescending(p=>p.Id).Take(5))
                    {
                        <div class="col-auto">
                                <div>
                                <a asp-action="Details" class="text-info" asp-route-id="@product.Id">
                                    <img src="@product.Image" width="120" height="120" style="border-radius:5px; border:1px solid #bbb9b9;" />
                                </a>
                                </div>
                                <div>
                                    <a asp-action="Details" class="text-info" asp-route-id="@product.Id">
                                        <text class="text-primary" style="font-size:18px;">@product.Name</text>
                                    </a>
                                    <br />
                                    @{
                                        if (product.SalePrice == 0)
                                        //할인행사 없을 때
                                        {
                                            <b style="color:dimgray;font-size:large">@product.Price 루블</b>
                                        }
                                        //할인행사 있을 때
                                        else
                                        {
                                            <b style="color:darkred;font-size:large">@product.SalePrice 루블</b>
                                            <b style="font-size:small"><del>@product.Price 루블</del></b>
                                        }
                                    }
                                </div>
                            
                        </div>
                    }

                    @{ 
                        if (Model.Count()>5)
                        {
                                        <div class="col-auto">
                                            <i class="fas fa-angle-double-right text-info"> 더보기</i>
                                        </div>
                        }
                    }
                    
                </div>
                </div>

      

}

Views/Shared/_IndexNewItemsPartial.cshtml
@model IEnumerable<ProductItemModel>

@if (Model.Count() > 0)
{
    <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px">
        <div class="row col-12">
            <h5 class="text-dark"><span class="badge badge-pill badge-info">New</span>&nbsp;신상품</h5>

        </div>

        <div class="row">

            @foreach (var product in Model.Where(p => p.ProductAd == "1" && p.IsNotVisible == false).OrderByDescending(p => p.Id).Take(6))
            {
                <div class="col-auto">
                    <div>
                        <a asp-action="Details" class="text-info" asp-route-id="@product.Id">
                            <img src="@product.Image" width="120" height="120" style="border-radius:5px; border:1px solid #bbb9b9;" />
                        </a>
                    </div>
                    <div>
                        <a asp-action="Details" class="text-info" asp-route-id="@product.Id">
                            <text class="text-primary" style="font-size:18px;">@product.Name</text>
                        </a>
                        <br />
                        @{
                            if (product.SalePrice == 0)
                            //할인행사 없을 때
                            {
                                <b style="color:dimgray;font-size:large">@product.Price 루블</b>
                            }
                            //할인행사 있을 때
                            else
                            {
                                <b style="color:darkred;font-size:large">@product.SalePrice 루블</b>
                                <b style="font-size:small"><del>@product.Price 루블</del></b>
                            }
                        }
                    </div>

                </div>
            }
            @{
                if (Model.Count() > 5)
                {
                    <div class="col-auto">
                        <i class="fas fa-angle-double-right text-info"> 더보기</i>
                    </div>
                }
            }


        </div>
    </div>

      

}

Views/Shared/_IndexSaleItemsPartial.cshtml
@model IEnumerable<ProductItemModel>

@if (Model.Count() > 0)
{
         <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px">
            
             <h5 class="text-dark"><span class="badge badge-pill badge-danger">Sale</span> &nbsp;할인행사 상품</h5>
            
             <div class="row">

                 @foreach (var product in Model.Where(p => p.SalePrice != 0 && p.IsNotVisible == false).OrderByDescending(p => p.Id).Take(5))
                 {
                     <div class="col-auto">
                         <div>
                             <a asp-action="Details" class="text-info" asp-route-id="@product.Id">
                                 <img src="@product.Image" width="120" height="120" style="border-radius:5px; border:1px solid #bbb9b9;" />
                             </a>
                         </div>
                         <div>
                             <a asp-action="Details" class="text-info" asp-route-id="@product.Id">
                                 <text class="text-primary" style="font-size:18px;">@product.Name</text>
                             </a>
                             <br />
                             @{
                                 if (product.SalePrice == 0)
                                 //할인행사 없을 때
                                 {
                                     <b style="color:dimgray;font-size:large">@product.Price 루블</b>
                                 }
                                 //할인행사 있을 때
                                 else
                                 {
                                     <b style="color:darkred;font-size:large">@product.SalePrice 루블</b>
                                     <b style="font-size:small"><del>@product.Price 루블</del></b>
                                 }
                             }
                         </div>

                     </div>
                 }

                 @{
                     if (Model.Count() > 5)
                     {
                         <div class="col-auto">
                             <i class="fas fa-angle-double-right text-info"> 더보기</i>
                         </div>
                     }
                 }

             </div>
                </div>

      

}

Views/Shared/_Layout.cshtml
@using Mosdong.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>한국상점 모스동</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />

    <link rel="stylesheet" type="text/css" href="~/DataTables/datatables.min.css" />


    <style>
        .dropdown-hover-all .dropdown-menu, .dropdown-hover > .dropdown-menu {
            margin: 0
        }
    </style>
</head>

<body class="lottemartdream">

    <header>
        <div class="lottemartdream">
            <div class="container">
                <nav class="navbar navbar-dark navbar-expand-lg navbar-toggleable-sm bg-primary mainmenu">
                    <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index"><text style="font-family:LotteMartDream">한국상점</text> <text style="font-family:Binggrae-Bold">모스동</text><span class="sr-only">(current)</span></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav">
                            <partial name="_LoginPartial" />
                        </ul>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav flex-grow-1">
                                @if (User.IsInRole(SD.ManagerUser))
                                {
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="dropdown00" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            상점 관리
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="dropdown00">
                                            <div class="dropdown dropright">
                                                <a class="dropdown-item dropdown-toggle" href="#" id="dropdown-layouts" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">카테고리</a>
                                                <div class="dropdown-menu" aria-labelledby="dropdown-layouts">
                                                    <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">카테고리 1</a>
                                                    <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">카테고리 2</a>
                                                    <a class="dropdown-item" asp-action="Index" asp-controller="MiniCategory" asp-area="Admin">카테고리 3</a>
                                                </div>
                                            </div>
                                            <a class="dropdown-item" asp-action="Index" asp-controller="ProductItem" asp-area="Admin">상품목록</a>
                                            <a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">쿠폰목록</a>
                                            <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Admin">직원계정</a>
                                            <div class="dropdown-divider"></div>
                                            <div class="dropdown dropright">
                                                <a class="dropdown-item dropdown-toggle" href="#" id="dropdown-layouts" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Layouts</a>
                                                <div class="dropdown-menu" aria-labelledby="dropdown-layouts">
                                                    <a class="dropdown-item" href="#">Basic</a>
                                                    <a class="dropdown-item" href="#">Compact Aside</a>
                                                    <div class="dropdown-divider"></div>
                                                    <div class="dropdown dropright">
                                                        <a class="dropdown-item dropdown-toggle" href="#" id="dropdown-layouts" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Custom</a>
                                                        <div class="dropdown-menu" aria-labelledby="dropdown-layouts">
                                                            <a class="dropdown-item" href="#">Fullscreen</a>
                                                            <a class="dropdown-item" href="#">Empty</a>
                                                            <div class="dropdown-divider"></div>
                                                            <a class="dropdown-item" href="#">Magic</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                }

                                @await Component.InvokeAsync("TopNav")


                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
            <div class="container">
                <div class="row py-3">
                    <div class="input-group col-9 form-inline">

                        <input type="text" class="form-control" placeholder="검색어를 입력하세요">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button">&nbsp;<i class="fas fa-search"></i></button>
                        </div>


                    </div>
                    @{
                        int? cartCount = HttpContextAccessor.HttpContext.Session.GetInt32(SD.ssShopingCartCount);
                    }
                    <div class="col-3 text-right">
                        <a asp-area="Customer" asp-controller="Cart" asp-action="Index" style="font-size:16pt;text-decoration:none">
                            <i class="fas fa-shopping-cart"></i>(@(cartCount ?? 0))
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color:#343a40;">
        <div class="container">
            &copy; @DateTime.Now.Year - Mosdong
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/6jljvrt59k204g0az00spikzz4cfbk1jwbvqsk3rbwvrglt4/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <script type="text/javascript" charset="utf8" src="~/DataTables/datatables.js"></script>

    <script src="https://kit.fontawesome.com/8cc909eb3b.js" crossorigin="anonymous"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("에러") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Views/Shared/_TableButtonCreatePartial.cshtml
@model int

<td style="text-align:right;">
    <div class="btn-group" role="group">
        <a class="btn btn-outline-primary" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit">수정</i>
        </a>
        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt">삭제</i>
        </a>
    </div>
</td>